# Generated by Django 5.2.17 on 2026-08-09 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_seconds', models.FloatField(default=5.0, help_text='How long each photo stays on screen, in seconds (0.1-100).', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Slideshow settings',
                'verbose_name_plural': 'Slideshow settings',
            },
        ),
    ]
