# Generated by Django 5.2.17 on 2026-08-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_slideshowsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
