# Generated by Django 5.2.17 on 2026-08-09 18:22

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_useridentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.photo_upload_path),
        ),
    ]
