# Generated by Django 5.2.17 on 2026-08-15 17:55

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_enabled', models.BooleanField(default=False, help_text='When on, uploaded photos are also copied to a Google Drive folder, and guests are offered to share that folder to their email.')),
                ('drive_folder_name', models.CharField(default=photos.models.default_drive_folder_name, help_text='Name of the Drive folder for this event. Reused if it already exists under the configured root folder; created otherwise.', max_length=200)),
                ('drive_folder_id', models.CharField(blank=True, max_length=100)),
                ('drive_folder_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Event settings',
                'verbose_name_plural': 'Event settings',
            },
        ),
        migrations.AddField(
            model_name='useridentity',
            name='drive_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
