# Generated by Django 5.2.17 on 2026-08-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_eventsettings_useridentity_drive_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='likes_enabled',
            field=models.BooleanField(default=True, help_text='When off, the heart/like button is hidden and the TV leaderboard is hidden.'),
        ),
    ]
