# Generated by Django 5.2.17 on 2026-08-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_eventsettings_likes_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='Auto-filled from the folder name above. To point to a different/existing folder instead, paste its Drive URL or ID here directly.', max_length=200),
        ),
    ]
