# Generated by Django 5.2.17 on 2026-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='drive_sharing_enabled',
            field=models.BooleanField(default=False, help_text='When on, every guest with an email on file is added as a reader on the Drive folder. When off, that access is revoked for all of them.'),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='drive_permission_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
