# Generated by Django 5.2.17 on 2026-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_multi_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='Auto-filled from the event name above. To point to a different/existing folder instead, paste its Drive URL or ID here directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
