# Generated by Django 5.2.17 on 2026-08-15 20:54

import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_event_drive_folder_id_alter_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tv_layout',
            field=models.CharField(choices=[('slideshow', 'Photo slideshow'), ('whiteboard', 'Collective whiteboard')], default='slideshow', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='whiteboard_enabled',
            field=models.BooleanField(default=False, help_text='When on, guests get a button on the home page to draw on the collective whiteboard.'),
        ),
        migrations.AddField(
            model_name='event',
            name='whiteboard_image',
            field=models.ImageField(blank=True, upload_to=photos.models.whiteboard_board_path),
        ),
        migrations.CreateModel(
            name='WhiteboardDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=photos.models.whiteboard_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_drawings', to='photos.event')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
