# Generated by Django 5.2.17 on 2026-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_event_tv_layout_event_whiteboard_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Wi-Fi password'),
        ),
        migrations.AddField(
            model_name='event',
            name='wifi_qr_enabled',
            field=models.BooleanField(default=False, help_text='When on, a second QR code to join the Wi-Fi is shown next to the upload QR code on the TV screen.'),
        ),
        migrations.AddField(
            model_name='event',
            name='wifi_security',
            field=models.CharField(choices=[('WPA', 'WPA / WPA2 / WPA3'), ('WEP', 'WEP'), ('NOPASS', 'Open (no password)')], default='WPA', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='wifi_ssid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wi-Fi network name (SSID)'),
        ),
    ]
