# Generated by Django 5.2.17 on 2026-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_event_wifi_password_event_wifi_qr_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tv_bottom_right',
            field=models.CharField(choices=[('leaderboard', 'Leaderboard'), ('none', 'Nothing')], default='leaderboard', max_length=20),
        ),
    ]
