# Generated by Django 5.2.17 on 2026-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_event_wifi_password_event_wifi_qr_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_host', models.CharField(blank=True, help_text="Address guests' phones use to reach this server (e.g. 192.168.1.13:8000), encoded in the upload QR code. Auto-detected on first use; change it here if it's wrong or your network changes, no restart needed.", max_length=255)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
