# Generated by Django 5.2.17 on 2026-08-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='server_host',
            field=models.CharField(blank=True, help_text="Address guests' phones use to reach this server (e.g. 192.168.1.13:8000), encoded in the upload QR code. Pre-filled from the address used to load the setup wizard; change it here if it's wrong or your network changes, no restart needed.", max_length=255),
        ),
    ]
