# Generated by Django 5.2.17 on 2026-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_alter_sitesettings_server_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='drive_root_folder_id',
            field=models.CharField(blank=True, help_text="ID of the Drive folder under which each event creates its own subfolder. Set from the setup wizard's Drive step (or the GOOGLE_DRIVE_ROOT_FOLDER_ID env var, which takes priority if set).", max_length=200),
        ),
    ]
