# Generated by Django 5.2.17 on 2026-08-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_event_tv_bottom_right'),
        ('photos', '0016_sitesettings_drive_root_folder_id'),
    ]

    operations = [
    ]
