# Generated by Django 5.2.17 on 2026-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_admininvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvite',
            name='invitee_name',
            field=models.CharField(default='', help_text='Who this invite link was generated for.', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admininvite',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
