# Generated by Django 5.2.17 on 2026-08-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_admininvite_invitee_name_admininvite_revoked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='server_host',
        ),
    ]
