# Generated by Django 5.2.17 on 2026-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_remove_sitesettings_server_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='server_host',
            field=models.CharField(blank=True, help_text="Address guests' phones use to reach this server (e.g. 192.168.1.13:8000), encoded in the upload QR code. Only ever set by scanning the verification QR code on the admin account page — that's what proves the address is actually reachable. Leave blank to fall back to whatever address loaded the current page.", max_length=255),
        ),
    ]
