# Generated by Django 5.2.17 on 2026-08-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_sitesettings_server_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Gmail address used to send admin password-reset emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email_app_password',
            field=models.CharField(blank=True, help_text='Gmail app password (not the account password) for support_email.', max_length=255),
        ),
    ]
