# Generated by Django 5.2.17 on 2026-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_sitesettings_support_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_email_verified',
            field=models.BooleanField(default=False, help_text="Set once the verification link sent to the admin's own email has been clicked. Reset to False whenever support_email is changed."),
        ),
    ]
