# Generated by Django 5.2.17 on 2026-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0023_sitesettings_support_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='support_email_app_password',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='support_email_verified',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Gmail address used to send admin password-reset emails. Auto-filled from whichever Google account is connected via OAuth2 (see gmail_service.py) — never typed in directly, since Google no longer accepts plain-password Gmail logins.', max_length=254),
        ),
    ]
