# Generated by Django 5.2.17 on 2026-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0024_remove_sitesettings_support_email_app_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
