# Generated by Django 5.2.17 on 2026-09-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0029_remove_sitesettings_wifi_qr_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tv_bottom_right',
            field=models.CharField(choices=[('leaderboard', 'Classement'), ('none', 'Rien')], default='leaderboard', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='tv_layout',
            field=models.CharField(choices=[('slideshow', 'Diaporama photo'), ('whiteboard', 'Whiteboard collectif')], default='slideshow', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mot de passe Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='wifi_security',
            field=models.CharField(choices=[('WPA', 'WPA / WPA2 / WPA3'), ('WEP', 'WEP'), ('NOPASS', 'Ouvert (sans mot de passe)')], default='WPA', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='wifi_ssid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du réseau Wi-Fi (SSID)'),
        ),
    ]
