# Generated by Django 5.2.17 on 2026-09-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0030_alter_event_tv_bottom_right_alter_event_tv_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wifi_verified',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
